name: Build and Publish Docker Image
on:
  push:
    branches:
      - main

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build api/ -t dsourav155/qr-code-api:latest

      - name: Push Docker image
        run: |
          docker login -u dsourav155 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push dsourav155/qr-code-api:latest