name: Build and push images to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'

jobs:
  push-images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build images
        run: |
          docker build ./api/ -t dsourav155/qr-code-api:latest
          docker build ./front-end-nextjs/ -t dsourav155/qr-code-frontend:latest
      - name: push images to docker hub
        run: |
          docker login -u dsourav155 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push dsourav155/qr-code-api:latest
          docker push dsourav155/qr-code-frontend:latest

